config/routes.rb
Rails.application.routes.draw do

  root to: "lists#index"

  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "Already in list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<nav class="navbar navbar-dark bg-dark d-flex">
  <%= link_to root_path, class: "text-decoration-none" do %>
    <p class="text-warning m-2 ms-3"><i class="fa-solid fa-ticket"></i> Watch Lists</p>
  <% end %>
  <%= link_to "New List", new_list_path(@list), class: "text-decoration-none text-warning me-3" %>
</nav>

<div class="new_list">
  <h1>New Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back to the list", list_path(@list), class: 'btn btn-light' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<nav class="navbar navbar-dark bg-dark d-flex">
    <p class="text-warning m-2 ms-3"><i class="fa-solid fa-ticket"></i> Watch Lists</p>
    <%= link_to "New List", new_list_path(@list), class: "text-decoration-none text-warning me-3" %>
</nav>

<div class="banner text-bg-success" style="">
  <div class="container">
    <h1>Create your lists!</h1>
    <p>Save all the movies you want to see</p>
    <%= link_to "Add a new list", new_list_path(@list), class: "btn btn-light" %>
  </div>
</div>

<div class="my-3 p-3">
  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list), class: "text-decoration-none" do %>
        <div class="card-category text-bg-dark rounded">
          <h5 class="card-title"><%= list.name %></h5>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<nav class="navbar navbar-dark bg-dark d-flex">
  <%= link_to root_path, class: "text-decoration-none" do %>
    <p class="text-warning m-2 ms-3"><i class="fa-solid fa-ticket"></i> Watch Lists</p>
  <% end %>
    <%= link_to "Your Watchlists", root_path, class: "text-decoration-none text-warning me-3" %>
</nav>

<div class ="new_list">
  <h1>New List</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back to the lists", root_path(@lists), class: 'btn btn-light' %>
</div>

app/views/lists/show.html.erb
<nav class="navbar navbar-dark bg-dark d-flex">
  <%= link_to root_path, class: "text-decoration-none" do %>
    <p class="text-warning m-2 ms-3"><i class="fa-solid fa-ticket"></i> Watch Lists</p>
  <% end %>
  <%= link_to "Your list", list_path(@list), class: "text-decoration-none text-warning me-3" %>
</nav>

<div class="bookmark">
  <h1><%= @list.name %></h1>

  <div class="card mb-3" style="max-width: 540px;">
    <% @bookmarks.each do |bookmark| %>
      <div class="row g-0">
        <div class="col-md-4 bg-dark text-light">
          Movie
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= bookmark.movie.title %></h5>
            <p class="card-text">Synopsis : <%= bookmark.movie.overview %></p>
            <p class="card-text">Release at : <%= bookmark.movie.release_date %></p>
            <p class="card-text">Rating : <%= bookmark.movie.rating %>/10</p>
            <p class="card-text"><em><%= bookmark.comment %></em></p>
            <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none text-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to "Add a new bookmark", new_list_bookmark_path(@list), class: 'btn btn-primary' %>

  <%= link_to "Back to the lists", root_path, class: 'btn btn-light' %>
</div>